/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.Main;

import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Color;
import java.awt.event.WindowEvent;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Particular
 */
public class TelaLoja extends javax.swing.JFrame {

           URL url = getClass().getResource("/br/com/Main/Musicas/MenuMusic.wav");
           AudioClip audio = Applet.newAudioClip(url);  
    public TelaLoja() {
        initComponents();
        setLocation(Variaveis.telap1, Variaveis.telap2);
        setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        atualizaLoja();
        if(Variaveis.music == true){
            audio.play();
        }
        addWindowListener(new java.awt.event.WindowAdapter() {
            
            @Override
            public void windowClosing(WindowEvent e){
                TelaMenu tm = new TelaMenu();
                tm.setVisible(true);
                audio.stop();
            }
            
});   
        Color cor = new Color(26, 27, 29);      
        getContentPane().setBackground(cor);
      //  String imageNameicone = "src\\br\\com\\Main\\Imagens\\KmilaImgs\\KmilaGorda30x30.png";
        ImageIcon iconicone = new ImageIcon(getClass().getResource("/br/com/Main/Imagens/KmilaImgs/KmilaGorda30x30.png"));
        iconicone.getImage().flush();
        setIconImage(iconicone.getImage());   
    }
     
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CarrinhoImg2 = new javax.swing.JLabel();
        CarrinhoImg1 = new javax.swing.JLabel();
        CompraLapis = new javax.swing.JButton();
        CompraCaneta = new javax.swing.JButton();
        CompraBorracha = new javax.swing.JButton();
        CompraVIC = new javax.swing.JButton();
        CompraApontador = new javax.swing.JButton();
        CompraGrifa = new javax.swing.JButton();
        BurrachaImg = new javax.swing.JLabel();
        CustoBurracha = new javax.swing.JLabel();
        LapisImg = new javax.swing.JLabel();
        CustoLapis = new javax.swing.JLabel();
        CanetaImg = new javax.swing.JLabel();
        CustoCaneta = new javax.swing.JLabel();
        GrifaImg = new javax.swing.JLabel();
        CustoGrifa = new javax.swing.JLabel();
        ApontadorImg = new javax.swing.JLabel();
        CustoApontador = new javax.swing.JLabel();
        VicImg = new javax.swing.JLabel();
        CustoVIC = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        QuantBorracha = new javax.swing.JLabel();
        QuantLapis = new javax.swing.JLabel();
        QuantCaneta = new javax.swing.JLabel();
        QuantGrifa = new javax.swing.JLabel();
        QuantApontador = new javax.swing.JLabel();
        QuantVIC = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CompraLapis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Main/Imagens/BtnImgs/BtnComprarLoja.png"))); // NOI18N
        CompraLapis.setBorder(null);
        CompraLapis.setContentAreaFilled(false);
        CompraLapis.setFocusPainted(false);
        CompraLapis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CompraLapisMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CompraLapisMouseReleased(evt);
            }
        });
        CompraLapis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompraLapisActionPerformed(evt);
            }
        });
        getContentPane().add(CompraLapis, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 101, 43));

        CompraCaneta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Main/Imagens/BtnImgs/BtnComprarLoja.png"))); // NOI18N
        CompraCaneta.setBorder(null);
        CompraCaneta.setContentAreaFilled(false);
        CompraCaneta.setFocusPainted(false);
        CompraCaneta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CompraCanetaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CompraCanetaMouseReleased(evt);
            }
        });
        CompraCaneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompraCanetaActionPerformed(evt);
            }
        });
        getContentPane().add(CompraCaneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 103, 43));

        CompraBorracha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Main/Imagens/BtnImgs/BtnComprarLoja.png"))); // NOI18N
        CompraBorracha.setBorder(null);
        CompraBorracha.setContentAreaFilled(false);
        CompraBorracha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CompraBorracha.setFocusPainted(false);
        CompraBorracha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CompraBorrachaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CompraBorrachaMouseReleased(evt);
            }
        });
        CompraBorracha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompraBorrachaActionPerformed(evt);
            }
        });
        getContentPane().add(CompraBorracha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 103, 43));
        CompraBorracha.getAccessibleContext().setAccessibleDescription("");

        CompraVIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Main/Imagens/BtnImgs/BtnComprarLoja.png"))); // NOI18N
        CompraVIC.setBorder(null);
        CompraVIC.setContentAreaFilled(false);
        CompraVIC.setFocusPainted(false);
        CompraVIC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CompraVICMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CompraVICMouseReleased(evt);
            }
        });
        CompraVIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompraVICActionPerformed(evt);
            }
        });
        getContentPane().add(CompraVIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 277, 103, 43));

        CompraApontador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Main/Imagens/BtnImgs/BtnComprarLoja.png"))); // NOI18N
        CompraApontador.setBorder(null);
        CompraApontador.setContentAreaFilled(false);
        CompraApontador.setFocusPainted(false);
        CompraApontador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CompraApontadorMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CompraApontadorMouseReleased(evt);
            }
        });
        CompraApontador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompraApontadorActionPerformed(evt);
            }
        });
        getContentPane().add(CompraApontador, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 277, 101, 43));

        CompraGrifa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Main/Imagens/BtnImgs/BtnComprarLoja.png"))); // NOI18N
        CompraGrifa.setBorder(null);
        CompraGrifa.setContentAreaFilled(false);
        CompraGrifa.setFocusPainted(false);
        CompraGrifa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CompraGrifaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CompraGrifaMouseReleased(evt);
            }
        });
        CompraGrifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompraGrifaActionPerformed(evt);
            }
        });
        getContentPane().add(CompraGrifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 277, 101, 43));

        BurrachaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Main/Imagens/IcnImgs/Burracha.png"))); // NOI18N
        getContentPane().add(BurrachaImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        CustoBurracha.setForeground(new java.awt.Color(255, 255, 255));
        CustoBurracha.setText("Preço: $10");
        getContentPane().add(CustoBurracha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        LapisImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Main/Imagens/IcnImgs/Lapis.png"))); // NOI18N
        getContentPane().add(LapisImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        CustoLapis.setForeground(new java.awt.Color(255, 255, 255));
        CustoLapis.setText("Custo: 10");
        getContentPane().add(CustoLapis, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        CanetaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Main/Imagens/IcnImgs/Caneta.png"))); // NOI18N
        getContentPane().add(CanetaImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        CustoCaneta.setForeground(new java.awt.Color(255, 255, 255));
        CustoCaneta.setText("Custo: 10");
        getContentPane().add(CustoCaneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        GrifaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Main/Imagens/IcnImgs/GrifaTexto.png"))); // NOI18N
        getContentPane().add(GrifaImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        CustoGrifa.setForeground(new java.awt.Color(255, 255, 255));
        CustoGrifa.setText("Custo: 10");
        getContentPane().add(CustoGrifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        ApontadorImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Main/Imagens/IcnImgs/Apontador.png"))); // NOI18N
        getContentPane().add(ApontadorImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, 40));

        CustoApontador.setForeground(new java.awt.Color(255, 255, 255));
        CustoApontador.setText("Custo: 10");
        getContentPane().add(CustoApontador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        VicImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Main/Imagens/IcnImgs/Vic.png"))); // NOI18N
        getContentPane().add(VicImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        CustoVIC.setForeground(new java.awt.Color(255, 255, 255));
        CustoVIC.setText("Custo: 10");
        getContentPane().add(CustoVIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Main/Imagens/TxtImgs/Lojinha.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, 44));

        QuantBorracha.setForeground(new java.awt.Color(255, 255, 255));
        QuantBorracha.setText("x0");
        getContentPane().add(QuantBorracha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        QuantLapis.setForeground(new java.awt.Color(255, 255, 255));
        QuantLapis.setText("x0");
        getContentPane().add(QuantLapis, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        QuantCaneta.setForeground(new java.awt.Color(255, 255, 255));
        QuantCaneta.setText("x0");
        getContentPane().add(QuantCaneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        QuantGrifa.setForeground(new java.awt.Color(255, 255, 255));
        QuantGrifa.setText("x0");
        getContentPane().add(QuantGrifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 208, -1, -1));

        QuantApontador.setForeground(new java.awt.Color(255, 255, 255));
        QuantApontador.setText("x0");
        getContentPane().add(QuantApontador, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 211, -1, -1));

        QuantVIC.setForeground(new java.awt.Color(255, 255, 255));
        QuantVIC.setText("x0");
        getContentPane().add(QuantVIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 211, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Main/Imagens/IcnImgs/SetaVoltar.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 28));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("?");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 50, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void CompraGrifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompraGrifaActionPerformed
        if(VariaveisLoja.getDinheiro() >= VariaveisLoja.getPGrifa()){
           VariaveisLoja.setDinheiro(VariaveisLoja.getDinheiro() - VariaveisLoja.getPGrifa());
           VariaveisLoja.setQGrifa(VariaveisLoja.getQGrifa() + 1);
           VariaveisLoja.setPGrifa(VariaveisLoja.getQGrifa() * 20);
           atualizaLoja(); 
        }
    }//GEN-LAST:event_CompraGrifaActionPerformed

    private void CompraBorrachaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompraBorrachaActionPerformed
        if(VariaveisLoja.getDinheiro() >= VariaveisLoja.getPBorracha()){
           VariaveisLoja.setDinheiro(VariaveisLoja.getDinheiro() - VariaveisLoja.getPBorracha());
           VariaveisLoja.setQBorracha(VariaveisLoja.getQBorracha() + 1);
           VariaveisLoja.setPBorracha(VariaveisLoja.getQBorracha() * 10);
           atualizaLoja(); 
        }
    }//GEN-LAST:event_CompraBorrachaActionPerformed

    private void CompraLapisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompraLapisActionPerformed
        if(VariaveisLoja.getDinheiro() >= VariaveisLoja.getPLapis()){
           VariaveisLoja.setDinheiro(VariaveisLoja.getDinheiro() - VariaveisLoja.getPLapis());
           VariaveisLoja.setQLapis(VariaveisLoja.getQLapis() + 1);
           VariaveisLoja.setPLapis(VariaveisLoja.getQLapis() * 10);
           atualizaLoja(); 
        }
    }//GEN-LAST:event_CompraLapisActionPerformed

    private void CompraCanetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompraCanetaActionPerformed
        if(VariaveisLoja.getDinheiro() >= VariaveisLoja.getPCaneta()){
           VariaveisLoja.setDinheiro(VariaveisLoja.getDinheiro() - VariaveisLoja.getPCaneta());
           VariaveisLoja.setQCaneta(VariaveisLoja.getQCaneta() + 1);
           VariaveisLoja.setPCaneta(VariaveisLoja.getQCaneta() * 15);
           atualizaLoja(); 
        }
    }//GEN-LAST:event_CompraCanetaActionPerformed

    private void CompraApontadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompraApontadorActionPerformed
        if(VariaveisLoja.getDinheiro() >= VariaveisLoja.getPApontador()){
           VariaveisLoja.setDinheiro(VariaveisLoja.getDinheiro() - VariaveisLoja.getPApontador());
           VariaveisLoja.setQApontador(VariaveisLoja.getQApontador() + 1);
           VariaveisLoja.setPApontador(VariaveisLoja.getQApontador() * 30);
           atualizaLoja(); 
        }
    }//GEN-LAST:event_CompraApontadorActionPerformed

    private void CompraVICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompraVICActionPerformed
        if(VariaveisLoja.getDinheiro() >= VariaveisLoja.getPVic()){
           VariaveisLoja.setDinheiro(VariaveisLoja.getDinheiro() - VariaveisLoja.getPVic());
           VariaveisLoja.setQVic(VariaveisLoja.getQVic() + 1);
           VariaveisLoja.setPVic(VariaveisLoja.getPVic() + 50);
           Variaveis.somaDelayKmia(50);
           atualizaLoja(); 
        }
    }//GEN-LAST:event_CompraVICActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        TelaMenu tela = new TelaMenu();
        tela.setVisible(true);
        audio.stop();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CompraCanetaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompraCanetaMousePressed
      mudaBotaoPrecionar(CompraCaneta);
    }//GEN-LAST:event_CompraCanetaMousePressed

    private void CompraLapisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompraLapisMousePressed
        mudaBotaoPrecionar(CompraLapis);
    }//GEN-LAST:event_CompraLapisMousePressed

    private void CompraBorrachaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompraBorrachaMousePressed
        mudaBotaoPrecionar(CompraBorracha);
    }//GEN-LAST:event_CompraBorrachaMousePressed

    private void CompraGrifaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompraGrifaMousePressed
        mudaBotaoPrecionar(CompraGrifa);
    }//GEN-LAST:event_CompraGrifaMousePressed

    private void CompraApontadorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompraApontadorMousePressed
        mudaBotaoPrecionar(CompraApontador);
    }//GEN-LAST:event_CompraApontadorMousePressed

    private void CompraVICMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompraVICMousePressed
        mudaBotaoPrecionar(CompraVIC);
    }//GEN-LAST:event_CompraVICMousePressed

    private void CompraVICMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompraVICMouseReleased
        mudaBotaoDesprecionar(CompraVIC);
    }//GEN-LAST:event_CompraVICMouseReleased

    private void CompraBorrachaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompraBorrachaMouseReleased
        mudaBotaoDesprecionar(CompraBorracha);
    }//GEN-LAST:event_CompraBorrachaMouseReleased

    private void CompraLapisMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompraLapisMouseReleased
       mudaBotaoDesprecionar(CompraLapis);
    }//GEN-LAST:event_CompraLapisMouseReleased

    private void CompraCanetaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompraCanetaMouseReleased
        mudaBotaoDesprecionar(CompraCaneta);
    }//GEN-LAST:event_CompraCanetaMouseReleased

    private void CompraGrifaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompraGrifaMouseReleased
        mudaBotaoDesprecionar(CompraGrifa);
    }//GEN-LAST:event_CompraGrifaMouseReleased

    private void CompraApontadorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompraApontadorMouseReleased
        mudaBotaoDesprecionar(CompraApontador);
    }//GEN-LAST:event_CompraApontadorMouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TelaAjuda tl = new TelaAjuda();
        tl.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void mudaBotaoPrecionar(JButton botao){
      //  String imageName = "src/br/com/Main/Imagens/BtnImgs/BtnComprarLojaPressed.png"; // MUDEI AQUI
        ImageIcon icon = new ImageIcon(getClass().getResource("/br/com/Main/Imagens/BtnImgs/BtnComprarLojaPressed.png"));
        icon.getImage().flush();
        botao.setIcon( icon );
    }
    
    public void mudaBotaoDesprecionar(JButton botao){
     //   String imageName = "src/br/com/Main/Imagens/BtnImgs/BtnComprarLoja.png"; // MUDEI AQUI TBM
        ImageIcon icon = new ImageIcon(getClass().getResource("/br/com/Main/Imagens/BtnImgs/BtnComprarLoja.png"));
        icon.getImage().flush();
        botao.setIcon( icon );
    }
    
    
    public void atualizaLoja(){
        //Quantidade:      
        QuantGrifa.setText("x" + VariaveisLoja.getQGrifa());
        QuantBorracha.setText("x" + VariaveisLoja.getQBorracha());
        QuantLapis.setText("x" + VariaveisLoja.getQLapis());
        QuantApontador.setText("x" + VariaveisLoja.getQApontador());
        QuantCaneta.setText("x" + VariaveisLoja.getQCaneta());
        QuantVIC.setText("x" + VariaveisLoja.getQVic());
        // Custo:
        CustoBurracha.setText("Preço: $" + VariaveisLoja.getPBorracha());
        CustoApontador.setText("Preço: $" + VariaveisLoja.getPApontador());
        CustoCaneta.setText("Preço: $" + VariaveisLoja.getPCaneta());
        CustoGrifa.setText("Preço: $" + VariaveisLoja.getPGrifa());
        CustoLapis.setText("Preço: $" + VariaveisLoja.getPLapis());
        CustoVIC.setText("Preço: $" + VariaveisLoja.getPVic());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLoja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApontadorImg;
    private javax.swing.JLabel BurrachaImg;
    private javax.swing.JLabel CanetaImg;
    private javax.swing.JLabel CarrinhoImg1;
    private javax.swing.JLabel CarrinhoImg2;
    private javax.swing.JButton CompraApontador;
    private javax.swing.JButton CompraBorracha;
    private javax.swing.JButton CompraCaneta;
    private javax.swing.JButton CompraGrifa;
    private javax.swing.JButton CompraLapis;
    private javax.swing.JButton CompraVIC;
    private javax.swing.JLabel CustoApontador;
    private javax.swing.JLabel CustoBurracha;
    private javax.swing.JLabel CustoCaneta;
    private javax.swing.JLabel CustoGrifa;
    private javax.swing.JLabel CustoLapis;
    private javax.swing.JLabel CustoVIC;
    private javax.swing.JLabel GrifaImg;
    private javax.swing.JLabel LapisImg;
    private javax.swing.JLabel QuantApontador;
    private javax.swing.JLabel QuantBorracha;
    private javax.swing.JLabel QuantCaneta;
    private javax.swing.JLabel QuantGrifa;
    private javax.swing.JLabel QuantLapis;
    private javax.swing.JLabel QuantVIC;
    private javax.swing.JLabel VicImg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
