/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.Main;

import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Color;
import java.awt.Toolkit;
import static java.lang.Thread.sleep;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author Particular
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        setLocation(750, 300);
        setResizable(false);
        ImageIcon iconicone = new ImageIcon(getClass().getResource("/br/com/Main/Imagens/KmilaImgs/KmilaGorda30x30.png"));
        iconicone.getImage().flush();
        setIconImage(iconicone.getImage());       
        Color cor = new Color(26, 27, 29);
        getContentPane().setBackground(cor);
       // setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("C:/Users/Particular/Desktop/Pastas/Projeto KmilaTheGame/KmilaGorda20x20.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        butaum = new javax.swing.JButton();
        Kmila = new javax.swing.JLabel();
        Caneta = new javax.swing.JLabel();
        burracha = new javax.swing.JLabel();
        Apontador = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnCreditos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Main/Imagens/TxtImgs/KmilaTheGame.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        butaum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Main/Imagens/BtnImgs/ButaumInicio.png"))); // NOI18N
        butaum.setBorderPainted(false);
        butaum.setContentAreaFilled(false);
        butaum.setFocusPainted(false);
        butaum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butaumMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                butaumMousePressed(evt);
            }
        });
        butaum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaumActionPerformed(evt);
            }
        });
        getContentPane().add(butaum, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 175, 80));

        Kmila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Main/Imagens/KmilaImgs/Camilalvl1.png"))); // NOI18N
        getContentPane().add(Kmila, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        Caneta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Main/Imagens/IcnImgs/Caneta.png"))); // NOI18N
        getContentPane().add(Caneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 86, -1, -1));

        burracha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Main/Imagens/IcnImgs/Burracha.png"))); // NOI18N
        getContentPane().add(burracha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        Apontador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Main/Imagens/IcnImgs/Apontador.png"))); // NOI18N
        getContentPane().add(Apontador, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 185, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Main/Imagens/IcnImgs/Lapis.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 95, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Main/Imagens/IcnImgs/GrifaTexto.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 267, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Main/Imagens/IcnImgs/Lapis.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 296, -1, -1));

        BtnCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Main/Imagens/BtnImgs/BtnCreditos.png"))); // NOI18N
        BtnCreditos.setContentAreaFilled(false);
        BtnCreditos.setFocusPainted(false);
        BtnCreditos.setFocusable(false);
        BtnCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnCreditosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BtnCreditosMouseReleased(evt);
            }
        });
        BtnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreditosActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 70, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butaumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaumActionPerformed
        // TODO add your handling code here:
        Variaveis.telap1 = (int) getLocation().getX();
        Variaveis.telap2 = (int) getLocation().getY();
        TelaMenu menu = new TelaMenu();
        menu.setVisible(true);
        setVisible(false);
     //   Musicas.playMusica("C:/Users/Particular/Desktop/Pastas/Projeto KmilaTheGame/Musicas/MenuMusic.wav");
     
    }//GEN-LAST:event_butaumActionPerformed

    private void butaumMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butaumMousePressed
        ImageIcon icon = new ImageIcon(getClass().getResource("/br/com/Main/Imagens/BtnImgs/ButaumInicioPrecionado.png"));
        icon.getImage().flush();
        butaum.setIcon( icon );
    }//GEN-LAST:event_butaumMousePressed

    private void butaumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butaumMouseExited
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(getClass().getResource("/br/com/Main/Imagens/BtnImgs/ButaumInicio.png"));
        icon.getImage().flush();
        butaum.setIcon( icon );
    }//GEN-LAST:event_butaumMouseExited

    private void BtnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreditosActionPerformed
        TelaCreditos tl = new TelaCreditos();
        tl.setVisible(true);
    }//GEN-LAST:event_BtnCreditosActionPerformed

    private void BtnCreditosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCreditosMousePressed
        ImageIcon icon = new ImageIcon(getClass().getResource("/br/com/Main/Imagens/BtnImgs/BtnCreditosPressed.png"));
        icon.getImage().flush();
        BtnCreditos.setIcon( icon );
    }//GEN-LAST:event_BtnCreditosMousePressed

    private void BtnCreditosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCreditosMouseReleased
        ImageIcon icon = new ImageIcon(getClass().getResource("/br/com/Main/Imagens/BtnImgs/BtnCreditos.png"));
        icon.getImage().flush();
        BtnCreditos.setIcon( icon );
    }//GEN-LAST:event_BtnCreditosMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apontador;
    private javax.swing.JButton BtnCreditos;
    private javax.swing.JLabel Caneta;
    private javax.swing.JLabel Kmila;
    private javax.swing.JLabel burracha;
    private javax.swing.JButton butaum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
